services:
  - type: web
    name: auraweave-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: web
    name: auraweave-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_streamlit.py --server.port=$PORT --server.address=0.0.0.0 --server.enableCORS=false
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0  
      - key: API_ENDPOINT
        value: https://auraweave-api.onrender.com